volumes:
  msc-mongo-data:
  msc-redis-data:


services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passwort
    volumes:
      - msc-mongo-data:/data/db
  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - msc-redis-data:/data
